import time
t1 = time.time()
# sys.path.insert(0, r'N:\VersionControl\thirdparty\Windowspython3_packages_nlp')
from transformers import pipeline
print(pipeline)
t2 = time.time()

# โหลดโมเดล
# classifier = pipeline("sentiment-analysis", device=0)
classifier = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

# ข้อความหลายข้อความ
notes = [
    "The textures look great, but the lighting could use some adjustment.",
    "Impressive work! Just minor tweaks needed on the shadows.",
    "The composition is solid, but the colors feel a bit too saturated.",
    "The background looks great, but the main subject feels out of focus.",
    "Excellent work! Everything seems polished and ready to go.",
    "The details are nice, but the edges appear too sharp.",
    "Great job on the overall design, but the proportions need adjustment.",
    "The animation feels fluid, but some movements seem unnatural.",
    "The reflections are too strong and distract from the subject.",
    "The perspective is slightly off in this shot.",
    "This is a good start, but it needs more depth and complexity.",
    "Beautiful rendering, but the shadows feel too harsh.",
    "I love the atmosphere, but the colors seem inconsistent.",
    "The main subject looks great, but the background feels flat.",
    "Good work, but the texture on the surface looks repetitive.",
    "The lighting is nearly perfect, but it needs a bit more contrast.",
    "The overall look is clean, but the highlights are too bright.",
    "The color palette is lovely, but it could use more variety.",
    "The model looks good, but the edges seem too jagged.",
    "The camera angle feels awkward; try a different perspective.",
    "The animation timing feels slightly off in this sequence.",
    "This version is much better, but the details are still lacking.",
    "The scene is well composed, but it could use more dynamic lighting.",
    "The textures are realistic, but the scale seems incorrect.",
    "The focus is great, but the blur effect feels unnatural.",
    "The light source is unclear; try defining it better.",
    "The mood is excellent, but it lacks some storytelling elements.",
    "The motion blur is too strong and detracts from the action.",
    "The reflections are realistic, but they need more subtlety.",
    "The background elements seem disconnected from the foreground.",
    "The character's proportions look off; adjust the arms and legs.",
    "This is a solid improvement, but the shadows feel inconsistent.",
    "The scene feels a bit empty; try adding more props or details.",
    "Great lighting! However, the textures need more definition.",
    "The transitions in the animation feel abrupt; smooth them out.",
    "The render quality is good, but the colors need more balance.",
    "The pose looks stiff; try something more dynamic.",
    "The environment looks great, but the character feels out of place.",
    "The edges of the object are too sharp; try softening them.",
    "The depth of field effect is overdone and distracts from the subject.",
    "The light direction is inconsistent with the shadows.",
    "The animation speed feels too fast in certain parts.",
    "The textures look stretched; adjust the UV mapping.",
    "The model's details are nice, but the silhouette feels weak.",
    "The camera movement is too shaky; try stabilizing it.",
    "The scene lacks a clear focal point.",
    "The shading is good, but the materials need more refinement.",
    "The proportions are better, but the pose looks unnatural.",
    "The animation feels lifeless; add more secondary motion.",
    "The lighting is good, but it doesn't match the environment.",
    "The shadows are missing in some areas and feel inconsistent.",
    "The surface looks too reflective for this material.",
    "The character's expression is too neutral; add more emotion.",
    "The props look out of scale with the rest of the scene.",
    "The texture detail is great, but the color palette feels dull.",
    "The highlights are blown out; reduce their intensity.",
    "The ambient occlusion feels too strong and looks unnatural.",
    "The scene feels too busy; simplify the background.",
    "The animation lacks weight; add more follow-through.",
    "The render quality is good, but it needs more post-processing.",
    "The light falloff is too abrupt; make it more gradual.",
    "The materials look good, but the transparency is too high.",
    "The edges of the shadow are too sharp; soften them slightly.",
    "The object placement feels random; align them better.",
    "The glow effect is overdone and makes the scene look artificial.",
    "The textures are repetitive; add more variation.",
    "The character animation is good, but the lipsync is off.",
    "The camera framing is too tight; give it more breathing room.",
    "The fog effect is too strong and obscures the details.",
    "The background looks good, but the foreground lacks detail.",
    "The lighting setup is great, but the rim light is missing.",
    "The transition between scenes feels abrupt; make it smoother.",
    "The render looks flat; add more contrast to the lighting.",
    "The props are good, but their positioning feels unnatural.",
    "The reflection map doesn't match the environment.",
    "The dynamic range is too low; the scene feels dull.",
    "The character rigging looks off; the joints bend unnaturally.",
    "The particle effects look great, but they need more variation.",
    "The ground texture is blurry; increase its resolution.",
    "The motion feels too linear; add more curves to the animation.",
    "The glass material looks solid; increase its transparency.",
    "The scene feels too dark; increase the overall brightness.",
    "The shadows are too soft; add more definition.",
    "The lighting setup is good, but it lacks atmosphere.",
    "The animation loops well, but the transition is noticeable.",
    "The render has noise; increase the sample count.",
    "The hair simulation looks unnatural; refine the movement.",
    "The facial expressions are stiff; make them more dynamic.",
    "The metallic material looks too dull; make it shinier.",
    "The vegetation looks good, but it lacks variation in color.",
    "The skybox doesn't match the lighting in the scene.",
    "The motion trails are too pronounced; make them subtler.",
    "The background blur is inconsistent with the depth of field.",
    "Impressive work! Just minor tweaks needed on the shadows.",
    "The composition is solid, but the colors feel a bit too saturated.",
    "The background looks great, but the main subject feels out of focus.",
    "Excellent work! Everything seems polished and ready to go.",
    "The details are nice, but the edges appear too sharp.",
    "Great job on the overall design, but the proportions need adjustment.",
    "The animation feels fluid, but some movements seem unnatural.",
    "The reflections are too strong and distract from the subject.",
    "The perspective is slightly off in this shot.",
    "This is a good start, but it needs more depth and complexity.",
    "Beautiful rendering, but the shadows feel too harsh.",
    "I love the atmosphere, but the colors seem inconsistent.",
    "The main subject looks great, but the background feels flat.",
    "Good work, but the texture on the surface looks repetitive.",
    "The lighting is nearly perfect, but it needs a bit more contrast.",
    "The overall look is clean, but the highlights are too bright.",
    "The color palette is lovely, but it could use more variety.",
    "The model looks good, but the edges seem too jagged.",
    "The camera angle feels awkward; try a different perspective.",
    "The animation timing feels slightly off in this sequence.",
    "This version is much better, but the details are still lacking.",
    "The scene is well composed, but it could use more dynamic lighting.",
    "The textures are realistic, but the scale seems incorrect.",
    "The focus is great, but the blur effect feels unnatural.",
    "The light source is unclear; try defining it better.",
    "The mood is excellent, but it lacks some storytelling elements.",
    "The motion blur is too strong and detracts from the action.",
    "The reflections are realistic, but they need more subtlety.",
    "The background elements seem disconnected from the foreground.",
    "The character's proportions look off; adjust the arms and legs.",
    "This is a solid improvement, but the shadows feel inconsistent.",
    "The scene feels a bit empty; try adding more props or details.",
    "Great lighting! However, the textures need more definition.",
    "The transitions in the animation feel abrupt; smooth them out.",
    "The render quality is good, but the colors need more balance.",
    "The pose looks stiff; try something more dynamic.",
    "The environment looks great, but the character feels out of place.",
    "The edges of the object are too sharp; try softening them.",
    "The depth of field effect is overdone and distracts from the subject.",
    "The light direction is inconsistent with the shadows.",
    "The animation speed feels too fast in certain parts.",
    "The textures look stretched; adjust the UV mapping.",
    "The model's details are nice, but the silhouette feels weak.",
    "The camera movement is too shaky; try stabilizing it.",
    "The scene lacks a clear focal point.",
    "The shading is good, but the materials need more refinement.",
    "The proportions are better, but the pose looks unnatural.",
    "The animation feels lifeless; add more secondary motion.",
    "The lighting is good, but it doesn't match the environment.",
    "The shadows are missing in some areas and feel inconsistent.",
    "The surface looks too reflective for this material.",
    "The character's expression is too neutral; add more emotion.",
    "The props look out of scale with the rest of the scene.",
    "The texture detail is great, but the color palette feels dull.",
    "The highlights are blown out; reduce their intensity.",
    "The ambient occlusion feels too strong and looks unnatural.",
    "The scene feels too busy; simplify the background.",
    "The animation lacks weight; add more follow-through.",
    "The render quality is good, but it needs more post-processing.",
    "The light falloff is too abrupt; make it more gradual.",
    "The materials look good, but the transparency is too high.",
    "The edges of the shadow are too sharp; soften them slightly.",
    "The object placement feels random; align them better.",
    "The glow effect is overdone and makes the scene look artificial.",
    "The textures are repetitive; add more variation.",
    "The character animation is good, but the lipsync is off.",
    "The camera framing is too tight; give it more breathing room.",
    "The fog effect is too strong and obscures the details.",
    "The background looks good, but the foreground lacks detail.",
    "The lighting setup is great, but the rim light is missing.",
    "The transition between scenes feels abrupt; make it smoother.",
    "The render looks flat; add more contrast to the lighting.",
    "The props are good, but their positioning feels unnatural.",
    "The reflection map doesn't match the environment.",
    "The dynamic range is too low; the scene feels dull.",
    "The character rigging looks off; the joints bend unnaturally.",
    "The particle effects look great, but they need more variation.",
    "The ground texture is blurry; increase its resolution.",
    "The motion feels too linear; add more curves to the animation.",
    "The glass material looks solid; increase its transparency.",
    "The scene feels too dark; increase the overall brightness.",
    "The shadows are too soft; add more definition.",
    "The lighting setup is good, but it lacks atmosphere.",
    "The animation loops well, but the transition is noticeable.",
    "The render has noise; increase the sample count.",
    "The hair simulation looks unnatural; refine the movement.",
    "The facial expressions are stiff; make them more dynamic.",
    "The metallic material looks too dull; make it shinier.",
    "The vegetation looks good, but it lacks variation in color.",
    "The skybox doesn't match the lighting in the scene.",
    "The motion trails are too pronounced; make them subtler.",
    "The background blur is inconsistent with the depth of field.",
    "Impressive work! Just minor tweaks needed on the shadows.",
    "The composition is solid, but the colors feel a bit too saturated.",
    "The background looks great, but the main subject feels out of focus.",
    "Excellent work! Everything seems polished and ready to go.",
    "The details are nice, but the edges appear too sharp.",
    "Great job on the overall design, but the proportions need adjustment.",
    "The animation feels fluid, but some movements seem unnatural.",
    "The reflections are too strong and distract from the subject.",
    "The perspective is slightly off in this shot.",
    "This is a good start, but it needs more depth and complexity.",
    "Beautiful rendering, but the shadows feel too harsh.",
    "I love the atmosphere, but the colors seem inconsistent.",
    "The main subject looks great, but the background feels flat.",
    "Good work, but the texture on the surface looks repetitive.",
    "The lighting is nearly perfect, but it needs a bit more contrast.",
    "The overall look is clean, but the highlights are too bright.",
    "The color palette is lovely, but it could use more variety.",
    "The model looks good, but the edges seem too jagged.",
    "The camera angle feels awkward; try a different perspective.",
    "The animation timing feels slightly off in this sequence.",
    "This version is much better, but the details are still lacking.",
    "The scene is well composed, but it could use more dynamic lighting.",
    "The textures are realistic, but the scale seems incorrect.",
    "The focus is great, but the blur effect feels unnatural.",
    "The light source is unclear; try defining it better.",
    "The mood is excellent, but it lacks some storytelling elements.",
    "The motion blur is too strong and detracts from the action.",
    "The reflections are realistic, but they need more subtlety.",
    "The background elements seem disconnected from the foreground.",
    "The character's proportions look off; adjust the arms and legs.",
    "This is a solid improvement, but the shadows feel inconsistent.",
    "The scene feels a bit empty; try adding more props or details.",
    "Great lighting! However, the textures need more definition.",
    "The transitions in the animation feel abrupt; smooth them out.",
    "The render quality is good, but the colors need more balance.",
    "The pose looks stiff; try something more dynamic.",
    "The environment looks great, but the character feels out of place.",
    "The edges of the object are too sharp; try softening them.",
    "The depth of field effect is overdone and distracts from the subject.",
    "The light direction is inconsistent with the shadows.",
    "The animation speed feels too fast in certain parts.",
    "The textures look stretched; adjust the UV mapping.",
    "The model's details are nice, but the silhouette feels weak.",
    "The camera movement is too shaky; try stabilizing it.",
    "The scene lacks a clear focal point.",
    "The shading is good, but the materials need more refinement.",
    "The proportions are better, but the pose looks unnatural.",
    "The animation feels lifeless; add more secondary motion.",
    "The lighting is good, but it doesn't match the environment.",
    "The shadows are missing in some areas and feel inconsistent.",
    "The surface looks too reflective for this material.",
    "The character's expression is too neutral; add more emotion.",
    "The props look out of scale with the rest of the scene.",
    "The texture detail is great, but the color palette feels dull.",
    "The highlights are blown out; reduce their intensity.",
    "The ambient occlusion feels too strong and looks unnatural.",
    "The scene feels too busy; simplify the background.",
    "The animation lacks weight; add more follow-through.",
    "The render quality is good, but it needs more post-processing.",
    "The light falloff is too abrupt; make it more gradual.",
    "The materials look good, but the transparency is too high.",
    "The edges of the shadow are too sharp; soften them slightly.",
    "The object placement feels random; align them better.",
    "The glow effect is overdone and makes the scene look artificial.",
    "The textures are repetitive; add more variation.",
    "The character animation is good, but the lipsync is off.",
    "The camera framing is too tight; give it more breathing room.",
    "The fog effect is too strong and obscures the details.",
    "The background looks good, but the foreground lacks detail.",
    "The lighting setup is great, but the rim light is missing.",
    "The transition between scenes feels abrupt; make it smoother.",
    "The render looks flat; add more contrast to the lighting.",
    "The props are good, but their positioning feels unnatural.",
    "The reflection map doesn't match the environment.",
    "The dynamic range is too low; the scene feels dull.",
    "The character rigging looks off; the joints bend unnaturally.",
    "The particle effects look great, but they need more variation.",
    "The ground texture is blurry; increase its resolution.",
    "The motion feels too linear; add more curves to the animation.",
    "The glass material looks solid; increase its transparency.",
    "The scene feels too dark; increase the overall brightness.",
    "The shadows are too soft; add more definition.",
    "The lighting setup is good, but it lacks atmosphere.",
    "The animation loops well, but the transition is noticeable.",
    "The render has noise; increase the sample count.",
    "The hair simulation looks unnatural; refine the movement.",
    "The facial expressions are stiff; make them more dynamic.",
    "The metallic material looks too dull; make it shinier.",
    "The vegetation looks good, but it lacks variation in color.",
    "The skybox doesn't match the lighting in the scene.",
    "The motion trails are too pronounced; make them subtler.",
    "The background blur is inconsistent with the depth of field.",
    "Impressive work! Just minor tweaks needed on the shadows.",
    "The composition is solid, but the colors feel a bit too saturated.",
    "The background looks great, but the main subject feels out of focus.",
    "Excellent work! Everything seems polished and ready to go.",
    "The details are nice, but the edges appear too sharp.",
    "Great job on the overall design, but the proportions need adjustment.",
    "The animation feels fluid, but some movements seem unnatural.",
    "The reflections are too strong and distract from the subject.",
    "The perspective is slightly off in this shot.",
    "This is a good start, but it needs more depth and complexity.",
    "Beautiful rendering, but the shadows feel too harsh.",
    "I love the atmosphere, but the colors seem inconsistent.",
    "The main subject looks great, but the background feels flat.",
    "Good work, but the texture on the surface looks repetitive.",
    "The lighting is nearly perfect, but it needs a bit more contrast.",
    "The overall look is clean, but the highlights are too bright.",
    "The color palette is lovely, but it could use more variety.",
    "The model looks good, but the edges seem too jagged.",
    "The camera angle feels awkward; try a different perspective.",
    "The animation timing feels slightly off in this sequence.",
    "This version is much better, but the details are still lacking.",
    "The scene is well composed, but it could use more dynamic lighting.",
    "The textures are realistic, but the scale seems incorrect.",
    "The focus is great, but the blur effect feels unnatural.",
    "The light source is unclear; try defining it better.",
    "The mood is excellent, but it lacks some storytelling elements.",
    "The motion blur is too strong and detracts from the action.",
    "The reflections are realistic, but they need more subtlety.",
    "The background elements seem disconnected from the foreground.",
    "The character's proportions look off; adjust the arms and legs.",
    "This is a solid improvement, but the shadows feel inconsistent.",
    "The scene feels a bit empty; try adding more props or details.",
    "Great lighting! However, the textures need more definition.",
    "The transitions in the animation feel abrupt; smooth them out.",
    "The render quality is good, but the colors need more balance.",
    "The pose looks stiff; try something more dynamic.",
    "The environment looks great, but the character feels out of place.",
    "The edges of the object are too sharp; try softening them.",
    "The depth of field effect is overdone and distracts from the subject.",
    "The light direction is inconsistent with the shadows.",
    "The animation speed feels too fast in certain parts.",
    "The textures look stretched; adjust the UV mapping.",
    "The model's details are nice, but the silhouette feels weak.",
    "The camera movement is too shaky; try stabilizing it.",
    "The scene lacks a clear focal point.",
    "The shading is good, but the materials need more refinement.",
    "The proportions are better, but the pose looks unnatural.",
    "The animation feels lifeless; add more secondary motion.",
    "The lighting is good, but it doesn't match the environment.",
    "The shadows are missing in some areas and feel inconsistent.",
    "The surface looks too reflective for this material.",
    "The character's expression is too neutral; add more emotion.",
    "The props look out of scale with the rest of the scene.",
    "The texture detail is great, but the color palette feels dull.",
    "The highlights are blown out; reduce their intensity.",
    "The ambient occlusion feels too strong and looks unnatural.",
    "The scene feels too busy; simplify the background.",
    "The animation lacks weight; add more follow-through.",
    "The render quality is good, but it needs more post-processing.",
    "The light falloff is too abrupt; make it more gradual.",
    "The materials look good, but the transparency is too high.",
    "The edges of the shadow are too sharp; soften them slightly.",
    "The object placement feels random; align them better.",
    "The glow effect is overdone and makes the scene look artificial.",
    "The textures are repetitive; add more variation.",
    "The character animation is good, but the lipsync is off.",
    "The camera framing is too tight; give it more breathing room.",
    "The fog effect is too strong and obscures the details.",
    "The background looks good, but the foreground lacks detail.",
    "The lighting setup is great, but the rim light is missing.",
    "The transition between scenes feels abrupt; make it smoother.",
    "The render looks flat; add more contrast to the lighting.",
    "The props are good, but their positioning feels unnatural.",
    "The reflection map doesn't match the environment.",
    "The dynamic range is too low; the scene feels dull.",
    "The character rigging looks off; the joints bend unnaturally.",
    "The particle effects look great, but they need more variation.",
    "The ground texture is blurry; increase its resolution.",
    "The motion feels too linear; add more curves to the animation.",
    "The glass material looks solid; increase its transparency.",
    "The scene feels too dark; increase the overall brightness.",
    "The shadows are too soft; add more definition.",
    "The lighting setup is good, but it lacks atmosphere.",
    "The animation loops well, but the transition is noticeable.",
    "The render has noise; increase the sample count.",
    "The hair simulation looks unnatural; refine the movement.",
    "The facial expressions are stiff; make them more dynamic.",
    "The metallic material looks too dull; make it shinier.",
    "The vegetation looks good, but it lacks variation in color.",
    "The skybox doesn't match the lighting in the scene.",
    "The motion trails are too pronounced; make them subtler.",
    "The background blur is inconsistent with the depth of field.",
    "Impressive work! Just minor tweaks needed on the shadows.",
    "The composition is solid, but the colors feel a bit too saturated.",
    "The background looks great, but the main subject feels out of focus.",
    "Excellent work! Everything seems polished and ready to go.",
    "The details are nice, but the edges appear too sharp.",
    "Great job on the overall design, but the proportions need adjustment.",
    "The animation feels fluid, but some movements seem unnatural.",
    "The reflections are too strong and distract from the subject.",
    "The perspective is slightly off in this shot.",
    "This is a good start, but it needs more depth and complexity.",
    "Beautiful rendering, but the shadows feel too harsh.",
    "I love the atmosphere, but the colors seem inconsistent.",
    "The main subject looks great, but the background feels flat.",
    "Good work, but the texture on the surface looks repetitive.",
    "The lighting is nearly perfect, but it needs a bit more contrast.",
    "The overall look is clean, but the highlights are too bright.",
    "The color palette is lovely, but it could use more variety.",
    "The model looks good, but the edges seem too jagged.",
    "The camera angle feels awkward; try a different perspective.",
    "The animation timing feels slightly off in this sequence.",
    "This version is much better, but the details are still lacking.",
    "The scene is well composed, but it could use more dynamic lighting.",
    "The textures are realistic, but the scale seems incorrect.",
    "The focus is great, but the blur effect feels unnatural.",
    "The light source is unclear; try defining it better.",
    "The mood is excellent, but it lacks some storytelling elements.",
    "The motion blur is too strong and detracts from the action.",
    "The reflections are realistic, but they need more subtlety.",
    "The background elements seem disconnected from the foreground.",
    "The character's proportions look off; adjust the arms and legs.",
    "This is a solid improvement, but the shadows feel inconsistent.",
    "The scene feels a bit empty; try adding more props or details.",
    "Great lighting! However, the textures need more definition.",
    "The transitions in the animation feel abrupt; smooth them out.",
    "The render quality is good, but the colors need more balance.",
    "The pose looks stiff; try something more dynamic.",
    "The environment looks great, but the character feels out of place.",
    "The edges of the object are too sharp; try softening them.",
    "The depth of field effect is overdone and distracts from the subject.",
    "The light direction is inconsistent with the shadows.",
    "The animation speed feels too fast in certain parts.",
    "The textures look stretched; adjust the UV mapping.",
    "The model's details are nice, but the silhouette feels weak.",
    "The camera movement is too shaky; try stabilizing it.",
    "The scene lacks a clear focal point.",
    "The shading is good, but the materials need more refinement.",
    "The proportions are better, but the pose looks unnatural.",
    "The animation feels lifeless; add more secondary motion.",
    "The lighting is good, but it doesn't match the environment.",
    "The shadows are missing in some areas and feel inconsistent.",
    "The surface looks too reflective for this material.",
    "The character's expression is too neutral; add more emotion.",
    "The props look out of scale with the rest of the scene.",
    "The texture detail is great, but the color palette feels dull.",
    "The highlights are blown out; reduce their intensity.",
    "The ambient occlusion feels too strong and looks unnatural.",
    "The scene feels too busy; simplify the background.",
    "The animation lacks weight; add more follow-through.",
    "The render quality is good, but it needs more post-processing.",
    "The light falloff is too abrupt; make it more gradual.",
    "The materials look good, but the transparency is too high.",
    "The edges of the shadow are too sharp; soften them slightly.",
    "The object placement feels random; align them better.",
    "The glow effect is overdone and makes the scene look artificial.",
    "The textures are repetitive; add more variation.",
    "The character animation is good, but the lipsync is off.",
    "The camera framing is too tight; give it more breathing room.",
    "The fog effect is too strong and obscures the details.",
    "The background looks good, but the foreground lacks detail.",
    "The lighting setup is great, but the rim light is missing.",
    "The transition between scenes feels abrupt; make it smoother.",
    "The render looks flat; add more contrast to the lighting.",
    "The props are good, but their positioning feels unnatural.",
    "The reflection map doesn't match the environment.",
    "The dynamic range is too low; the scene feels dull.",
    "The character rigging looks off; the joints bend unnaturally.",
    "The particle effects look great, but they need more variation.",
    "The ground texture is blurry; increase its resolution.",
    "The motion feels too linear; add more curves to the animation.",
    "The glass material looks solid; increase its transparency.",
    "The scene feels too dark; increase the overall brightness.",
    "The shadows are too soft; add more definition.",
    "The lighting setup is good, but it lacks atmosphere.",
    "The animation loops well, but the transition is noticeable.",
    "The render has noise; increase the sample count.",
    "The hair simulation looks unnatural; refine the movement.",
    "The facial expressions are stiff; make them more dynamic.",
    "The metallic material looks too dull; make it shinier.",
    "The vegetation looks good, but it lacks variation in color.",
    "The skybox doesn't match the lighting in the scene.",
    "The motion trails are too pronounced; make them subtler.",
    "The background blur is inconsistent with the depth of field.",
    "Impressive work! Just minor tweaks needed on the shadows.",
    "The composition is solid, but the colors feel a bit too saturated.",
    "The background looks great, but the main subject feels out of focus.",
    "Excellent work! Everything seems polished and ready to go.",
    "The details are nice, but the edges appear too sharp.",
    "Great job on the overall design, but the proportions need adjustment.",
    "The animation feels fluid, but some movements seem unnatural.",
    "The reflections are too strong and distract from the subject.",
    "The perspective is slightly off in this shot.",
    "This is a good start, but it needs more depth and complexity.",
    "Beautiful rendering, but the shadows feel too harsh.",
    "I love the atmosphere, but the colors seem inconsistent.",
    "The main subject looks great, but the background feels flat.",
    "Good work, but the texture on the surface looks repetitive.",
    "The lighting is nearly perfect, but it needs a bit more contrast.",
    "The overall look is clean, but the highlights are too bright.",
    "The color palette is lovely, but it could use more variety.",
    "The model looks good, but the edges seem too jagged.",
    "The camera angle feels awkward; try a different perspective.",
    "The animation timing feels slightly off in this sequence.",
    "This version is much better, but the details are still lacking.",
    "The scene is well composed, but it could use more dynamic lighting.",
    "The textures are realistic, but the scale seems incorrect.",
    "The focus is great, but the blur effect feels unnatural.",
    "The light source is unclear; try defining it better.",
    "The mood is excellent, but it lacks some storytelling elements.",
    "The motion blur is too strong and detracts from the action.",
    "The reflections are realistic, but they need more subtlety.",
    "The background elements seem disconnected from the foreground.",
    "The character's proportions look off; adjust the arms and legs.",
    "This is a solid improvement, but the shadows feel inconsistent.",
    "The scene feels a bit empty; try adding more props or details.",
    "Great lighting! However, the textures need more definition.",
    "The transitions in the animation feel abrupt; smooth them out.",
    "The render quality is good, but the colors need more balance.",
    "The pose looks stiff; try something more dynamic.",
    "The environment looks great, but the character feels out of place.",
    "The edges of the object are too sharp; try softening them.",
    "The depth of field effect is overdone and distracts from the subject.",
    "The light direction is inconsistent with the shadows.",
    "The animation speed feels too fast in certain parts.",
    "The textures look stretched; adjust the UV mapping.",
    "The model's details are nice, but the silhouette feels weak.",
    "The camera movement is too shaky; try stabilizing it.",
    "The scene lacks a clear focal point.",
    "The shading is good, but the materials need more refinement.",
    "The proportions are better, but the pose looks unnatural.",
    "The animation feels lifeless; add more secondary motion.",
    "The lighting is good, but it doesn't match the environment.",
    "The shadows are missing in some areas and feel inconsistent.",
    "The surface looks too reflective for this material.",
    "The character's expression is too neutral; add more emotion.",
    "The props look out of scale with the rest of the scene.",
    "The texture detail is great, but the color palette feels dull.",
    "The highlights are blown out; reduce their intensity.",
    "The ambient occlusion feels too strong and looks unnatural.",
    "The scene feels too busy; simplify the background.",
    "The animation lacks weight; add more follow-through.",
    "The render quality is good, but it needs more post-processing.",
    "The light falloff is too abrupt; make it more gradual.",
    "The materials look good, but the transparency is too high.",
    "The edges of the shadow are too sharp; soften them slightly.",
    "The object placement feels random; align them better.",
    "The glow effect is overdone and makes the scene look artificial.",
    "The textures are repetitive; add more variation.",
    "The character animation is good, but the lipsync is off.",
    "The camera framing is too tight; give it more breathing room.",
    "The fog effect is too strong and obscures the details.",
    "The background looks good, but the foreground lacks detail.",
    "The lighting setup is great, but the rim light is missing.",
    "The transition between scenes feels abrupt; make it smoother.",
    "The render looks flat; add more contrast to the lighting.",
    "The props are good, but their positioning feels unnatural.",
    "The reflection map doesn't match the environment.",
    "The dynamic range is too low; the scene feels dull.",
    "The character rigging looks off; the joints bend unnaturally.",
    "The particle effects look great, but they need more variation.",
    "The ground texture is blurry; increase its resolution.",
    "The motion feels too linear; add more curves to the animation.",
    "The glass material looks solid; increase its transparency.",
    "The scene feels too dark; increase the overall brightness.",
    "The shadows are too soft; add more definition.",
    "The lighting setup is good, but it lacks atmosphere.",
    "The animation loops well, but the transition is noticeable.",
    "The render has noise; increase the sample count.",
    "The hair simulation looks unnatural; refine the movement.",
    "The facial expressions are stiff; make them more dynamic.",
    "The metallic material looks too dull; make it shinier.",
    "The vegetation looks good, but it lacks variation in color.",
    "The skybox doesn't match the lighting in the scene.",
    "The motion trails are too pronounced; make them subtler.",
    "The background blur is inconsistent with the depth of field.",
    "The character's clothing lacks detail in the fabric."
]

t3 = time.time()
# ประมวลผลทั้ง Batch
results = classifier(notes)
for note, result in zip(notes, results):
    sentiment = result['label']
    score = result['score']
    interpretation = "Feedback from client" if sentiment == "NEGATIVE" else "Approved"
    print(f"Note: {note}")
    print(f"{interpretation} (Score: {score:.2f})")
    print("-" * 50)

print('import time : {}'.format(t2-t1))
print('working time : {}'.format(time.time()-t3))
